# Netlify 設定ファイル
[build]
  # ビルドコマンド不要（静的サイト）
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HTTPS強制
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    
    # カメラ・マイクアクセス許可
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    # JavaScript最適化
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # CSS最適化
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    # HTML キャッシュ
    Cache-Control = "public, max-age=3600"

# SPA設定（必要に応じて）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# カスタムドメイン設定例
# [[redirects]]
#   from = "http://your-domain.com/*"
#   to = "https://your-domain.com/:splat"
#   status = 301
#   force = true